[package]
name = "intrd-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
env_logger = "0.11.8"
kstat-rs = "0.2.4"
libc = "0.2.169"
libsyslog = "0.1.1"
log = "0.4.25"
nix = "0.29.0"
signal-hook = "0.3.17"
simplelog = "0.12.2"
syslog = "7.0.0"
